<!-- <script src="<?php //echo $this->url('home',array('action' =>'index'));?>/login-tmp/modernizr.js" type="text/javascript"></script> -->
<!--<script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script> -->
<link href="<?php echo $this->url('home', array('action' =>'index'));?>login-tmp/reset.css" rel="stylesheet">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet prefetch">
    <!-- <link href="<?php //echo $this->url('home', array('action' =>'index'));?>login-tmp/font-awesome.min.css" rel="stylesheet">  -->
    <!-- <link href="<?php //echo $this->url('home', array('action' =>'index'));?>/login-tmp/style.css" rel="stylesheet"></link> -->
    </link>
</link>
<style type="text/css">
* {
    -ms-box-sizing: border-box;
    -moz-box-sizing: border-box;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    /*margin: 0;*/
    padding: -;
    /*border: 0;*/
}

html, body {
    width: 100% ;
    height: 100% ;
    background: url(https://static.pexels.com/photos/27341/pexels-photo-27341.jpg) repeat fixed;
    /*background: url(http://financialtribune.com/sites/default/files/field/image/04_Roads.jpg) no-repeat center center fixed;*/
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    font-family: 'Open Sans', sans-serif !important;
    font-weight: 200;
    z-index: 0;
    /*-webkit-filter: blur(5px);*/
}


/*body {
    
    
    background-size: cover;
}*/

.login {
    /*position: fixed;*/
    position: relative;
    height: 50px;
    /*top: 350px ;*/
    width: 290px;
    /*width: 250px;*/
    /*bottom: 0;*/
    

    display: table;
    margin: 170px auto auto auto;
    background: #fff;
    border-radius: 4px;
    z-index: 1 ;
     /*width: 60%;*/
    /*left: 50%; (100%-60%)/2
    top: 50%;*/

}

.logogeo{
        /*vertical-align: middle;
        box-sizing: border-box;*/
        /*position: absolute;
        top: 110%;
        left: 10%;
        width: 300px;*/
}

.legend {
    position: relative;
    width: 100%;
    display: block;
    background: #004d9c;
    /*background: #FF7052;*/
    padding: 15px;
    color: #fff;
    font-size: 20px;
    text-align: left;
}

.legend:after {
    content: "";
    /*background-image: url(http://simpleicon.com/wp-content/uploads/multy-user.png);*/
    background-size: 100px 100px;
    background-repeat: no-repeat;
    background-position: 152px -16px;
    opacity: 0.06;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    position: absolute;
}

.input {
    position: relative;
    width: 90%;
    margin: 15px auto;
}

.input span {
    position: absolute;
    display: block;
    color: #d4d4d4;
    left: 10px;
    top: 8px;
    font-size: 20px;
}

.input input {
    width: 100%;
    padding: 10px 5px 10px 40px;
    display: block;
    border: 1px solid #EDEDED;
    border-radius: 4px;
    transition: 0.2s ease-out;
    color: #a1a1a1;
}

.input input:focus {
    padding: 10px 5px 10px 10px;
    outline: 0;
    /*border-color: #FF7052;*/
    border-color: #004d9c;
}


.submit {
    width: 45px;
    height: 45px;
    display: block;
    margin: 0 auto -15px auto;
    background: #fff;
    border-radius: 100%;
    /*border: 1px solid #FF7052;*/
    border: 1px solid #004d9c;
    /*color: #FF7052;*/
    color: #004d9c;
    font-size: 24px;
    cursor: pointer;
    box-shadow: 0px 0px 0px 7px #fff;
    transition: 0.2s ease-out;
}

.submit:hover, .submit:focus {
    /*background: #FF7052;*/
    background: #004d9c;
    color: #fff;
    outline: 0;
}

.feedback {
    position: absolute;
    bottom: -70px;
    width: 100%;
    text-align: center;
    color: #fff;
    background: #2ecc71;
    padding: 10px 0;
    font-size: 12px;
    display: none;
    opacity: 0;
}

.feedback:before {
    bottom: 100%;
    left: 50%;
    border: solid transparent;
    content: "";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
    border-color: rgba(46, 204, 113, 0);
    border-bottom-color: #2ecc71;
    border-width: 10px;
    margin-left: -10px;
}
.submit:after{
    top:10;

}
.mensaj{
    position: absolute;
    bottom: -450px;
    width: 100%;
    text-align: center;
    color: #fff;
    background: #e03626;
    padding: 10px 0;
    font-size: 16px;

}

.mensaj:before {
    bottom: 100%;
    left: 47%;
    border: solid transparent;
    content: "";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
    border-color: rgba(46, 204, 113, 0);
    border-bottom-color: #e03626;
    border-width: 10px;
    margin-left: -10px;
}
.center {
/*position: absolute;*/
/*top:0;
left:0;
right:0;
bottom:0;*/
/*margin: auto;*/
/*background: #83C24A;*/
/*height: 100px;*/
/*width:10%;*/
/*box-shadow: 0 0 4px rgba(0,0,0,.3);*/
}
</style>

<?php
$title = 'Inicia sesión';
$this->headTitle($title);
$form = $this->form;
?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" language="javascript" src="Scripts/jquery.BgImageTransition.js"></script>

<div class="container">
    <div class="row">
         <div> 
            <?php
                    // $this->headTitle("Login usuarios");
                    $form = $this->form;
                    echo $this->form()->openTag($form);
            ?>
            <div >
                <!-- <img src="<?php echo $this->basePath('img/logo-geotest.png')?>" style="text-align: center;" width="290px" height="100"></img> -->
            <div class="login">
                <fieldset>
                    <legend class="legend">
                        Login
                    </legend>
                    <div class="input">
                        <input placeholder="E-mail" name="correo" required type="email"/>
                        <span>
                            <i class="fa fa-envelope-o">
                            </i>
                        </span>
                    </div>
                    <div class="input">
                        <input placeholder="Contraseña" name="pass" required type="password"/>
                        <span>
                            <i class="fa fa-lock">
                            </i>
                        </span>
                    </div>
                    <button class="submit" name="submit" type="submit">
                        <i class="fa fa-long-arrow-right">
                        </i>
                    </button>
                </fieldset>
                <div class="feedback">
                    login successful
                    <br/>
                    redirecting...
                </div>
            <?php  echo $this->form()->closeTag(); ?>            
            </div>
            <?php if( $message['msg'] != ""):?>
                <div class="mensaj"><p><?php echo $message['msg']; ?></p></div>
            <?php endif;?> 
            </div>
                           
        </div>
    </div>
</div>