<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Jhoanna '. $this->translate('Jhoanna'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath('css/style.css'))
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            //->prependFile($this->basePath() . '/js/bootbox.min.js')
            ->prependFile($this->basePath('js/bootbox.min.js'))
            //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            //->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath('js/jquery.min.js'))
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>        
    </head>

    <body>
    <!-- MODAL LOADING AJAX -->
            <div style="display:none" class="loading-modal">
                <!--<div>
                    <img src="<?php //echo $this->basePath('img/logo-geotest.png') ?>" alt="Geo Test" style="width:20%;"/>    
                </div>-->
                
                CARGANDO...<div class="cssload-spin"></div>
            </div>
        <!-- MODAL LOADING AJAX -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php// echo $this->url('home') ?>"><img src="<?php //echo $this->basePath('img/zf2-logo.png') ?>"/>&nbsp;<?php echo $this->translate('Jhoanna') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2016 - <?php echo date('Y') ?> by Jhoanna Ltd. <?php echo $this->translate('Todos los derechos reservados.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
<style type="text/css">
    .btn    {
                display: inline-block;
                padding: 6px 12px;
                margin-bottom: 0;
                font-size: 14px;
                font-weight: 400;
                line-height: 1.42857143;
                text-align: center;
                white-space: nowrap;
                vertical-align: middle;
                -ms-touch-action: manipulation;
                touch-action: manipulation;
                cursor: pointer;
                -webkit-user-select: none;
                 background-image: none;
                /*-moz-user-select: none;
                -ms-user-select: none;*/
                /*user-select: none;*/
                /*border: 1px solid transparent;*/
                /*border-radius: 4px;*/
            }


               .navbar-brand  {
                margin-left: auto;
                margin-right: 5px;
                padding-right: 0px!important;
                padding-left: 0px!important;
                padding-top: 8px;
                width: 53px;
                height: 35px;
                padding-bottom: 15px;
            }

    .navbar-inverse .navbar-nav>.active>a, .navbar-inverse .navbar-nav>.open>a {
                background-image: linear-gradient(to bottom,#515660 0,#515660 100%);
            }
    .dropdown-menu>li>a:hover, .dropdown-menu>li>a:focus, .dropdown-submenu:hover>a, .dropdown-submenu:focus>a {
                color: #fff;
                text-decoration: none;
                /*background-color: #1b498c;*/
                background-color: #2172f9;
                background-image: -moz-linear-gradient(top,#08c,#0077b3);
                background-image: -webkit-gradient(linear,0 0,0 100%,from(#08c),to(#0077b3));
                background-image: -webkit-linear-gradient(top,#08c,#0077b3);
                background-image: -o-linear-gradient(top,#08c,#0077b3);
                background-image: linear-gradient(to bottom,#1b498c,#1b498c);
                background-repeat: repeat-x;
                filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff0088cc',endColorstr='#ff0077b3',GradientType=0);
            }
    .container-fluid {
                /*padding-right: auto;
                padding-left: auto;
                margin-right: auto;
                margin-left: auto;*/
                margin: auto auto auto auto;
                padding: auto auto auto auto;
                border-color: #1B498C;
                /*background-color: #4285f4;*/
                background-color:#1B498C;
                /*background-color: linear-gradient(to bottom,#4285F4 0,#1B498C 100%);*/
                 /*#1B498C;*/
            }
</style>