<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/images/logo/horda.png'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath('login-p/assets/reset.min.css'))
            //->prependStylesheet($this->basePath('login-p/assets/css.css')."?family=Roboto:400,100,300,500,700,900")
            //->prependStylesheet($this->basePath('login-p/assets/css2.css')."?family=Montserrat:400,700")
            //->prependStylesheet($this->basePath('login-p/assets/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('login-p/css/style.css')); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
    </head>
<style type="text/css">
    body{ 
        /*background: url('https://static.pexels.com/photos/73988/fake-daylight-gobo-praca-notes-73988.jpeg') no-repeat center center fixed; */
         /*background: url('https://static.pexels.com/photos/343469/pexels-photo-343469.jpeg') no-repeat center center fixed; */
         /*background: url('<?php //echo $this->url('home', array('action' => 'index')); ?>images/background/city_skyline.jpeg') no-repeat center center fixed !important; */
         background: url("<?php echo $this->basePath('images/background/fake-daylight-gobo-praca-notes-73988.jpeg'); ?>") no-repeat center center fixed !important;
         /*background: url(https://static.pexels.com/photos/27341/pexels-photo-27341.jpg) no-repeat center center fixed; */
         -webkit-background-size: cover !important;
         -moz-background-size: cover !important;
         -o-background-size: cover !important;
         background-size: cover !important;
	    }
        
        .footer {
            color:white; 
            width: 100%;
            height: 50px;
            bottom: 0;
            position: fixed;
            text-align:center;
        }
</style>
    <body>
        <div class="container" align="center" margin="auto">
            <?php echo $this->inlineScript(); ?>
            <?php echo $this->content; ?>
            <?php print_r( $this->layout()->configGlobal ); ?>
        </div>
        <div class="footer">
            <p>&copy; 2016 - <?php echo date('Y') ?> <?php echo 'Jhoanna.'?> <?php echo $this->translate('Todos los derechos reservados') ?></p> 
        </div>
    </body>
</html>

